spring:
  application:
    name: ghostreport

  datasource:
    url: jdbc:postgresql://localhost:5432/ghostreport
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: user

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8081

app:
  upload-dir: uploads